server:
  port: 8888
  servlet:
    context-path: /demo

authority:
  datasource:
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/authority?autoReconnect=true
      username: postgres
      password: cycq8bh+ekIQxnwDLBgDSJksGRv2qr53WBbRHdBZd5qd1DyJJL+lfUK7Cfp/CApIga1KQVErLo19ppmCxMR5GOmSSz4xgJ50utL4mSDoZzsnVTP4Sr6s2cjAhaR657BntWL5tHliDlg/xb6euP7PkrcZSty4v+7zldcr1aumCl8=
      driverClassName: org.postgresql.Driver
      initialSize: 2
      minIdle: 2
      maxActive: 20

application:
  datasource:
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/application?autoReconnect=true
      username: postgres
      password: cycq8bh+ekIQxnwDLBgDSJksGRv2qr53WBbRHdBZd5qd1DyJJL+lfUK7Cfp/CApIga1KQVErLo19ppmCxMR5GOmSSz4xgJ50utL4mSDoZzsnVTP4Sr6s2cjAhaR657BntWL5tHliDlg/xb6euP7PkrcZSty4v+7zldcr1aumCl8=
      driverClassName: org.postgresql.Driver
      initialSize: 2
      minIdle: 2
      maxActive: 20

mybatis:
  # xml配置文件位置
  mapper-locations: classpath:conf/mybatis/mapper/**/*.xml
  typeAliasesPackage: org.ainy.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true